services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config 
    networks:
      - caddy

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    name: proxy
    driver: bridge
